apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-api
  name: api-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-api
status:
  loadBalancer: {}
